CREATE TABLE IF NOT EXISTS raw.player_box_scores (
    game_id VARCHAR NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    team_abbreviation VARCHAR NOT NULL,
    player_name VARCHAR NOT NULL,
    position VARCHAR,
    comment VARCHAR,
    minutes DOUBLE,
    starter BOOLEAN NOT NULL,
    did_not_play BOOLEAN NOT NULL,
    field_goals_made INTEGER,
    field_goals_attempted INTEGER,
    field_goal_percentage DOUBLE,
    three_pointers_made INTEGER,
    three_pointers_attempted INTEGER,
    three_point_percentage DOUBLE,
    free_throws_made INTEGER,
    free_throws_attempted INTEGER,
    free_throw_percentage DOUBLE,
    offensive_rebounds INTEGER,
    defensive_rebounds INTEGER,
    total_rebounds INTEGER,
    assists INTEGER,
    steals INTEGER,
    blocks INTEGER,
    turnovers INTEGER,
    personal_fouls INTEGER,
    points INTEGER,
    plus_minus DOUBLE,
    source_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (game_id, player_id)
);