"""NBA data-ingestion configuration."""

DEFAULT_SEASON = "2025-26"
DEFAULT_SEASON_TYPE = "Regular Season"

NBA_API_TIMEOUT_SECONDS = 60
NBA_API_REQUEST_DELAY_SECONDS = 0.75
NBA_API_RETRY_DELAY_SECONDS = 2.0
NBA_API_MAX_ATTEMPTS = 3
